In [1]:
# test of numpy basic functionalities
import numpy as np
print('Test of basic functionalities of numpy')
print('Numpy version: %s' % str(np.__version__))

Test of basic functionalities of numpy
Numpy version: 1.17.2


In [2]:
# display numpy array info
def displayNparrayInfo(na):
    if type(na) is not type(np.array([])):
        print('The input is not a numpy array')
        return
    print('Dimemsion: ', end='') # dimension
    print(na.ndim)
    print('Shape: ', end='') # shape
    print(na.shape)
    print('Size of data: ', end='') # size
    print(na.size)
    print('Type of data: ', end='') # data type
    print(na.dtype)
    print('Size of single data in byte: ', end='') # item size
    print(na.itemsize)

In [3]:
# generate by normal array
print('Generate numpy array by using normal array')
normal_int = np.array([[3,3,7],[8,9,6]])
displayNparrayInfo(normal_int)
normal_float = np.array([[6.7,7.7,8.1,9.2],[2.3,4.3,2.1,10.7]])
displayNparrayInfo(normal_float)

Generate numpy array by using normal array
Dimemsion: 2
Shape: (2, 3)
Size of data: 6
Type of data: int64
Size of single data in byte: 8
Dimemsion: 2
Shape: (2, 4)
Size of data: 8
Type of data: float64
Size of single data in byte: 8


In [4]:
# specify type
print('Specify data type')
spec_int32 = np.array([[3,3,7],[8,9,6]], dtype='int32')
displayNparrayInfo(spec_int32)

Specify data type
Dimemsion: 2
Shape: (2, 3)
Size of data: 6
Type of data: int32
Size of single data in byte: 4


In [5]:
# specific generation
print('sequence')
print(np.arange(0.0,10.0,np.pi))

print('one array')
print(np.ones([2,3,2]))

print('zero array')
print(np.zeros([4,3]))

print('unity matrix')
print(np.eye(7))

print('fill array')
print(np.full([3,2], 7.5))

sequence
[0.         3.14159265 6.28318531 9.42477796]
one array
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
zero array
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
unity matrix
[[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
fill array
[[7.5 7.5]
 [7.5 7.5]
 [7.5 7.5]]


In [6]:
# copy shape
print('ones with normal int array shape')
print(np.ones_like(normal_int))
print('zeros with normal float array shape')
print(np.zeros_like(normal_float))
print('fill with specific type array shape')
print(np.full_like(spec_int32, 7))

ones with normal int array shape
[[1 1 1]
 [1 1 1]]
zeros with normal float array shape
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]
fill with specific type array shape
[[7 7 7]
 [7 7 7]]


In [7]:
# linear space and array combination
print('generate linear space between 0 and 10 with size 4')
ls0 = np.linspace(1.0, 10.0, 4)
print(ls0)
print('same space without end')
ls1 = np.linspace(1.0, 10.0, 4, endpoint=False)
print(ls1)
print('combine two spaces')
print(np.concatenate((ls0, ls1)))
print('combine two arrays with different shapes')
try:
    print(np.concatenate((normal_float, ls0)))
except:
    print('failed, can\'t combine arrays with different shape')

generate linear space between 0 and 10 with size 4
[ 1.  4.  7. 10.]
same space without end
[1.   3.25 5.5  7.75]
combine two spaces
[ 1.    4.    7.   10.    1.    3.25  5.5   7.75]
combine two arrays with different shapes
failed, can't combine arrays with different shape


In [8]:
# test of array transformation
print('array transformations')
org = np.ones([2,3,2])
print('original array')
print(org)
print('result of reshape')
print(org.reshape([3,4]))
print('original remains')
print(org)
org.resize([3,4])
print('after resize, the original changes to')
print(org)
print('result of flatten')
print(org.flatten())
print('original remains')
print(org)
print('result of new type array')
print(org.astype(np.int32))
print('original remains')
print(org)
print('get corresponding python list of numpy array')
print(org.tolist())

array transformations
original array
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
result of reshape
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
original remains
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
after resize, the original changes to
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
result of flatten
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
original remains
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
result of new type array
[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]
original remains
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
get corresponding python list of numpy array
[[1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0]]
