In [1]:
import numpy as np
print('Test of numpy random and statistics functions')
print('Version of numpy: %s' % str(np.__version__))

Test of numpy random and statistics functions
Version of numpy: 1.17.2


In [2]:
import time
print('Use current second from UTC as random seed')
np.random.seed(int(time.mktime(time.gmtime()))%10000)

Use current second from UTC as random seed


In [3]:
print('Generate uniform random array')
print(np.random.rand(2,3))
print('Generate normal random array')
print(np.random.randn(2,3))

Generate uniform random array
[[0.2583185  0.4095276  0.31348493]
 [0.81731188 0.37391765 0.68937529]]
Generate normal random array
[[ 0.17655697 -1.03038005 -0.07547387]
 [ 1.91960702 -1.07922963 -0.65394993]]


In [4]:
print('Generate integer random array between 0 and 100')
print(np.random.randint(100,200,(2,3)))

Generate integer random array between 0 and 100
[[138 102 141]
 [114 184 146]]


In [5]:
org = np.random.randint(100,200,(5,2))
print('Original array')
print(org)
np.random.shuffle(org)
print('After shuffle')
print(org)
print('Use permutation to get')
print(np.random.permutation(org))
print('permutation doesn\'t change original array, it remains')
print(org)

Original array
[[150 100]
 [106 161]
 [108 110]
 [137 128]
 [183 145]]
After shuffle
[[150 100]
 [106 161]
 [137 128]
 [183 145]
 [108 110]]
Use permutation to get
[[183 145]
 [108 110]
 [137 128]
 [150 100]
 [106 161]]
permutation doesn't change original array, it remains
[[150 100]
 [106 161]
 [137 128]
 [183 145]
 [108 110]]


In [6]:
print('Extract randomly a new array from original one')
print(np.random.choice(org.flatten(), (3,2)))

Extract randomly a new array from original one
[[128 183]
 [145 108]
 [106 106]]


In [7]:
print('Uniform distribution')
print(np.random.uniform(0.0, 10.0, (2,7)))
print('Normal distribution')
print(np.random.normal(5.0, 2.0, (2,7)))
print('Poisson distribution')
print(np.random.poisson(7, (2,7)))

Uniform distribution
[[1.99995044 4.59955774 9.89019094 3.23431143 2.96626551 2.33868664
  7.60928474]
 [6.20126601 2.61489647 2.25328429 5.50323363 7.68320822 1.06129866
  8.78739608]]
Normal distribution
[[7.52187096 5.52567999 4.80394098 3.02352536 6.15108207 9.52608488
  4.13008368]
 [5.31167719 4.45773183 6.61968623 3.32589668 3.70347024 3.64640286
  5.97761294]]
Poisson distribution
[[ 6  5  4 12 12 13 11]
 [ 8  6  8  8  9 10  7]]


In [8]:
a = np.random.randint(0,100,[2,5])
print('Generate statistics target')
print(a)
print('sum: %f' % np.sum(a))
print('average of each row: ', end='')
print(np.mean(a, axis=1))
print('weighted average of each column: ', end='')
print(np.average(a, axis=0, weights=[0.7, 0.3]))
print('standard difference: %f' % np.std(a))
print('variance: %f' % np.var(a))

Generate statistics target
[[63 96 88 83 86]
 [18 26 26  6 93]]
sum: 585.000000
average of each row: [83.2 33.8]
weighted average of each column: [49.5 75.  69.4 59.9 88.1]
standard difference: 33.693471
variance: 1135.250000


In [9]:
print('minimum value: %d at %s' % (np.min(a), np.unravel_index(np.argmin(a), a.shape)))
print('maximum value: %d at %s' % (np.max(a), np.unravel_index(np.argmax(a), a.shape)))

minimum value: 6 at (1, 3)
maximum value: 96 at (0, 1)


In [10]:
print('peek to peek: %f' % np.ptp(a))
print('median: %d' % np.median(a))

peek to peek: 90.000000
median: 73


In [11]:
print('Generate a 5*5 array to calculate gradient')
b = np.random.rand(5,5) * 100
print(b)
grad_x, grad_y = np.gradient(b)
print('row gradient')
print(grad_x)
print('column gradient')
print(grad_y)

Generate a 5*5 array to calculate gradient
[[73.72519089 15.18913144 89.98425279 99.50110476 16.02607833]
 [65.9358858  28.96690248 13.84960524 69.07416444 27.39102432]
 [41.0587692  75.83741047 80.71487637 15.68610537 26.94792873]
 [75.06742133 40.01449258 39.30167731 51.06435956 70.38424285]
 [79.20364895 17.99303097 81.331496   61.99572613  4.68704134]]
row gradient
[[ -7.78930509  13.77777103 -76.13464755 -30.42694032  11.36494599]
 [-16.33321084  30.32413951  -4.63468821 -41.9074997    5.4609252 ]
 [  4.56576776   5.52379505  12.72603603  -9.00490244  21.49660927]
 [ 19.07243987 -28.92218975   0.30830981  23.15481038 -11.13044369]
 [  4.13622763 -22.02146161  42.02981869  10.93136657 -65.69720151]]
column gradient
[[-58.53605945   8.12953095  42.15598666 -36.97908723 -83.47502643]
 [-36.96898332 -26.04314028  20.05363098   6.77070954 -41.68314012]
 [ 34.77864127  19.82805358 -30.07565255 -26.88347382  11.26182336]
 [-35.05292875 -17.88287201   5.52493349  15.54128277  19.31988329]